######################################################################
# Automatically generated by qmake (3.1) Tue Jul 6 14:51:30 2021
######################################################################

TEMPLATE = app
TARGET = v4l2test
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Source/Headers/AboutWidget.h \
           Source/Headers/ActiveExposureWidget.h \
           Source/Headers/AutoReader.h \
           Source/Headers/AutoReaderWorker.h \
           Source/Headers/BaseLogger.h \
           Source/Headers/Camera.h \
           Source/Headers/CameraListCustomItem.h \
           Source/Headers/CameraObserver.h \
           Source/Headers/CustomGraphicsView.h \
           Source/Headers/CustomOptionWidget.h \
           Source/Headers/DeviationCalculator.h \
           Source/Headers/FrameObserver.h \
           Source/Headers/FrameObserverMMAP.h \
           Source/Headers/FrameObserverUSER.h \
           Source/Headers/ImageProcessingThread.h \
           Source/Headers/ImageTransform.h \
           Source/Headers/IOHelper.h \
           Source/Headers/LocalMutex.h \
           Source/Headers/LocalMutexLockGuard.h \
           Source/Headers/Logger.h \
           Source/Headers/MemoryHelper.h \
           Source/Headers/MyFrame.h \
           Source/Headers/MyFrameQueue.h \
           Source/Headers/SettingsActionWidget.h \
           Source/Headers/Thread.h \
           Source/Headers/V4L2Helper.h \
           Source/Headers/V4L2Viewer.h \
           Source/Headers/videodev2_av.h \
           Source/Headers/EnumeratorInterface/BooleanEnumerationControl.h \
           Source/Headers/EnumeratorInterface/ButtonEnumerationControl.h \
           Source/Headers/EnumeratorInterface/ControlEditWidget.h \
           Source/Headers/EnumeratorInterface/ControlsHolderWidget.h \
           Source/Headers/EnumeratorInterface/IControlEnumerationHolder.h \
           Source/Headers/EnumeratorInterface/Integer64EnumerationControl.h \
           Source/Headers/EnumeratorInterface/IntegerEnumerationControl.h \
           Source/Headers/EnumeratorInterface/ListEnumerationControl.h \
           Source/Headers/EnumeratorInterface/ListIntEnumerationControl.h \
           build/V4L2StaticLibrary/V4L2StaticLib_autogen/include/ui_ActiveExposureWidget.h \
           build/V4L2StaticLibrary/V4L2StaticLib_autogen/include/ui_ControlsHolderWidget.h \
           build/V4L2StaticLibrary/V4L2StaticLib_autogen/include/ui_V4L2Viewer.h
FORMS += Source/Resources/Forms/ActiveExposureWidget.ui \
         Source/Resources/Forms/ControlsHolderWidget.ui \
         Source/Resources/Forms/V4L2Viewer.ui
SOURCES += Source/main.cpp \
           build/CMakeFiles/feature_tests.c \
           build/CMakeFiles/feature_tests.cxx \
           build/V4L2StaticLibrary/qrc_V4L2Viewer.cpp \
           Source/Source/AboutWidget.cpp \
           Source/Source/ActiveExposureWidget.cpp \
           Source/Source/AutoReader.cpp \
           Source/Source/AutoReaderWorker.cpp \
           Source/Source/BaseLogger.cpp \
           Source/Source/Camera.cpp \
           Source/Source/CameraListCustomItem.cpp \
           Source/Source/CameraObserver.cpp \
           Source/Source/CustomGraphicsView.cpp \
           Source/Source/CustomOptionWidget.cpp \
           Source/Source/DeviationCalculator.cpp \
           Source/Source/FrameObserver.cpp \
           Source/Source/FrameObserverMMAP.cpp \
           Source/Source/FrameObserverUSER.cpp \
           Source/Source/ImageProcessingThread.cpp \
           Source/Source/ImageTransform.cpp \
           Source/Source/IOHelper.cpp \
           Source/Source/Logger.cpp \
           Source/Source/MyFrame.cpp \
           Source/Source/MyFrameQueue.cpp \
           Source/Source/SettingsActionWidget.cpp \
           Source/Source/Thread.cpp \
           Source/Source/V4L2Helper.cpp \
           Source/Source/V4L2Viewer.cpp \
           build/V4L2StaticLibrary/V4L2StaticLib_autogen/mocs_compilation.cpp \
           Source/Source/EnumeratorInterface/BooleanEnumerationControl.cpp \
           Source/Source/EnumeratorInterface/ButtonEnumerationControl.cpp \
           Source/Source/EnumeratorInterface/ControlEditWidget.cpp \
           Source/Source/EnumeratorInterface/ControlsHolderWidget.cpp \
           Source/Source/EnumeratorInterface/IControlEnumerationHolder.cpp \
           Source/Source/EnumeratorInterface/Integer64EnumerationControl.cpp \
           Source/Source/EnumeratorInterface/IntegerEnumerationControl.cpp \
           Source/Source/EnumeratorInterface/ListEnumerationControl.cpp \
           Source/Source/EnumeratorInterface/ListIntEnumerationControl.cpp \
           build/CMakeFiles/3.10.2/CompilerIdC/CMakeCCompilerId.c \
           build/CMakeFiles/3.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
RESOURCES += Source/Resources/V4L2Viewer.qrc
TRANSLATIONS += german.ts \
                Source/Resources/german.ts \
                Source/Resources/Translations/german.ts
