######################################################################
# Automatically generated by qmake (3.1) Fri May 21 15:40:03 2021
######################################################################

TEMPLATE = app
TARGET = v4l2test
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Source/Headers/AboutWidget.h \
           Source/Headers/BaseLogger.h \
           Source/Headers/Camera.h \
           Source/Headers/CameraObserver.h \
           Source/Headers/DeviationCalculator.h \
           Source/Headers/FrameObserver.h \
           Source/Headers/FrameObserverMMAP.h \
           Source/Headers/FrameObserverRead.h \
           Source/Headers/FrameObserverUSER.h \
           Source/Headers/ImageProcessingThread.h \
           Source/Headers/ImageTransform.h \
           Source/Headers/IOHelper.h \
           Source/Headers/LocalMutex.h \
           Source/Headers/LocalMutexLockGuard.h \
           Source/Headers/Logger.h \
           Source/Headers/MemoryHelper.h \
           Source/Headers/MyFrame.h \
           Source/Headers/MyFrameQueue.h \
           Source/Headers/Thread.h \
           Source/Headers/V4L2Helper.h \
           Source/Headers/V4L2Viewer.h \
           Source/Headers/videodev2_av.h
FORMS += Source/Resources/Forms/V4L2Viewer.ui
SOURCES += Source/main.cpp \
           Source/Source/AboutWidget.cpp \
           Source/Source/BaseLogger.cpp \
           Source/Source/Camera.cpp \
           Source/Source/CameraObserver.cpp \
           Source/Source/DeviationCalculator.cpp \
           Source/Source/FrameObserver.cpp \
           Source/Source/FrameObserverMMAP.cpp \
           Source/Source/FrameObserverRead.cpp \
           Source/Source/FrameObserverUSER.cpp \
           Source/Source/ImageProcessingThread.cpp \
           Source/Source/ImageTransform.cpp \
           Source/Source/IOHelper.cpp \
           Source/Source/Logger.cpp \
           Source/Source/MyFrame.cpp \
           Source/Source/MyFrameQueue.cpp \
           Source/Source/Thread.cpp \
           Source/Source/V4L2Helper.cpp \
           Source/Source/V4L2Viewer.cpp
RESOURCES += Source/Resources/V4L2Viewer.qrc
